// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6sFZjdAvvVvrRDeFuAAHECSB0s0fNybg',
    appId: '1:780019824315:web:ffef213184940d69045b9e',
    messagingSenderId: '780019824315',
    projectId: 'gestion-de-tickets-f3be8',
    authDomain: 'gestion-de-tickets-f3be8.firebaseapp.com',
    storageBucket: 'gestion-de-tickets-f3be8.appspot.com',
    measurementId: 'G-CHWW6DLZ0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoJeT5kxORmIeWl5TtH6jQSw2ffG9Lty4',
    appId: '1:780019824315:android:2c6f0c7130fe6d64045b9e',
    messagingSenderId: '780019824315',
    projectId: 'gestion-de-tickets-f3be8',
    storageBucket: 'gestion-de-tickets-f3be8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSlEeG0Rg9MnTfH09weZ3VgXJ2f2ZHuGM',
    appId: '1:780019824315:ios:25727b681f0908d6045b9e',
    messagingSenderId: '780019824315',
    projectId: 'gestion-de-tickets-f3be8',
    storageBucket: 'gestion-de-tickets-f3be8.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSlEeG0Rg9MnTfH09weZ3VgXJ2f2ZHuGM',
    appId: '1:780019824315:ios:25727b681f0908d6045b9e',
    messagingSenderId: '780019824315',
    projectId: 'gestion-de-tickets-f3be8',
    storageBucket: 'gestion-de-tickets-f3be8.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6sFZjdAvvVvrRDeFuAAHECSB0s0fNybg',
    appId: '1:780019824315:web:df2e00054cd35d11045b9e',
    messagingSenderId: '780019824315',
    projectId: 'gestion-de-tickets-f3be8',
    authDomain: 'gestion-de-tickets-f3be8.firebaseapp.com',
    storageBucket: 'gestion-de-tickets-f3be8.appspot.com',
    measurementId: 'G-BV10D8QLHL',
  );
}
